@@ -4,7 +4,6 @@ var $plugins =
[
{"name":"--------------------","status":false,"description":"------------------------------------------------------------","parameters":{}},
{"name":"YEP_CoreEngine","status":true,"description":"v1.25 Needed for the majority of Yanfly Engine Scripts. Also\ncontains bug fixes found inherently in RPG Maker.","parameters":{"---Screen---":"","Screen Width":"816","Screen Height":"624","Scale Battlebacks":"true","Scale Title":"true","Scale Game Over":"true","Open Console":"false","Reposition Battlers":"true","GameFont Load Timer":"0","Update Real Scale":"false","Collection Clear":"true","---Gold---":"","Gold Max":"99999999","Gold Font Size":"20","Gold Icon":"0","Gold Overlap":"A lotta","---Items---":"","Default Max":"999","Quantity Text Size":"20","---Parameters---":"","Max Level":"99","Actor MaxHP":"9999","Actor MaxMP":"9999","Actor Parameter":"999","Enemy MaxHP":"999999","Enemy MaxMP":"9999","Enemy Parameter":"999","---Battle---":"","Animation Rate":"4","Flash Target":"false","Show Events Transition":"true","Show Events Snapshot":"true","---Font---":"","Chinese Font":"GameFont","Korean Font":"GameFont","Default Font":"GameFont","Font Size":"26","Text Align":"left","---Windows---":"","Digit Grouping":"true","Line Height":"36","Icon Width":"32","Icon Height":"32","Face Width":"144","Face Height":"144","Window Padding":"18","Text Padding":"6","Window Opacity":"255","Gauge Outline":"true","Gauge Height":"18","Menu TP Bar":"true","---Window Colors---":"","Color: Normal":"0","Color: System":"4","Color: Crisis":"17","Color: Death":"18","Color: Gauge Back":"19","Color: HP Gauge 1":"10","Color: HP Gauge 2":"10","Color: MP Gauge 1":"1","Color: MP Gauge 2":"1","Color: MP Cost":"1","Color: Power Up":"24","Color: Power Down":"25","Color: TP Gauge 1":"6","Color: TP Gauge 2":"6","Color: TP Cost Color":"6"}},
{"name":"YEP_SaveEventLocations","status":true,"description":"Enable specified maps to memorize the locations of events\r\nwhen leaving and loading them upon reentering the map.","parameters":{}},
{"name":"YEP_MessageCore","status":true,"description":"v1.12 Adds more features to the Message Window to customized\nthe way your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward Key":"enter","Enable Fast Forward":"true","Word Wrapping":"false","Description Wrap":"false","Word Wrap Space":"false","---Font---":"","Font Name":"GameFont","Font Size":"26","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","Font Outline":"4","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]"}},
{"name":"YEP_PartySystem","status":true,"description":"v1.08 Replaces the default 'Formation' command with a new\nmenu for players to easily change party formations.","parameters":{"---General---":"","Max Battle Members":"4","Show Battle Command":"false","Enable Battle Command":"false","Battle Cooldown":"0","Maximum Followers":"4","EXP Distribution":"false","---Menu---":"","Help Window":"false","Text Alignment":"center","Change Command":"Change","Remove Command":"Remove","Revert Command":"Revert","Finish Command":"Finish","---Selection---":"","Empty Text":"","Actor Face":"false","Actor Sprite":"true","---List---":"","Remove Text":"Remove","Remove Icon":"16","Sprite Y Buffer":"16","In Party Text Color":"6","---Locking---":"","Lock First Actor":"false","Locked Icon":"195","Required Icon":"205","---Detail Window---":"","Enable Detail Window":"true","List Width":"300","Actor Parameters":"Parameters","Actor Equipment":"Equipment"}},
{"name":"YEP_WeaponUnleash","status":true,"description":"v1.01 Replace the Attack command or give it the option of\nhave a skill randomly occur when using it!","parameters":{}},
@ -57,5 +56,7 @@ var $plugins =
{"name":"stopbattletint","status":false,"description":"","parameters":{}},
{"name":"musicbug","status":true,"description":"A cache for WebAudio which keeps preloaded objects in memory while they are still recent or in use. Combined with TDDP Preload Manager, this should hopefully reduce BGM play lag to a minimum.","parameters":{}},
{"name":"--------------------","status":false,"description":"------------------------------------------------------------","parameters":{}},
{"name":"multi_timers_(mv)","status":true,"description":"Allows more than one timer running at once, with custom commands","parameters":{}}
{"name":"multi_timers_(mv)","status":true,"description":"Allows more than one timer running at once, with custom commands","parameters":{}},
{"name":"--------------------","status":false,"description":"------------------------------------------------------------","parameters":{}},
{"name":"YEP_SaveEventLocations","status":true,"description":"Enable specified maps to memorize the locations of events\r\nwhen leaving and loading them upon reentering the map.","parameters":{}}
];